language: python

# sudo false implies containerized builds
sudo: false

os:
  - linux
  - osx
  - windows
  
notifications:
  email:
    recipients:
      - schoi32@iit.edu
      - jrathin1@iit.edu
      - qmc-software@googlegroups.com
    on_success: always # default: change
    on_failure: always # default: always
    
python:
  - 3.7

env:
  global:
    # List package dependencies for conda
    - CONDA_DEPS="pytest numpy"
    # package name for test invocation
    - PACKAGENAME="QMCPy"

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install $CONDA_DEPS
- cd python_prototype
- pip install -r requirements.txt
- pip install codecov

install:
- pip install -e .

script:
- python -m unittest discover -s test/fasttests
- python -m unittest discover -s test/longtests
- coverage run --source=test/fasttests -m unittest discover -s test/fasttests


after_success:
- codecov