language: generic

# sudo false implies containerized builds
sudo: false

  
notifications:
  email:
    recipients:
      - schoi32@iit.edu
      - jrathin1@iit.edu
      - qmc-software@googlegroups.com
    on_success: change # default: change
    on_failure: always # default: always


matrix:
  include:
    - name: "Python 3.7.0 on Xenial Linux"
      os: linux
      env:
        - PYTHON_VERSION="3.7"
        - MINICONDAPATH="http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    - name: "Python 3.6.0 on Xenial Linux"
      os: linux
      env:
        - PYTHON_VERSION="3.6"
        - MINICONDAPATH="http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    - name: "Python 3.7.0 on macOS"
      os: osx
      env:
        - PYTHON_VERSION="3.7"
        - MINICONDAPATH="http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
      
env:
  global:
    # List package dependencies for conda
    - CONDA_DEPS="pytest numpy"
    # package name for test invocation
    - PACKAGENAME="QMCPy"

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget $MINICONDAPATH -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$PYTHON_VERSION
- source activate testenv
- conda install $CONDA_DEPS
- pip install --upgrade pip
- pip install codecov
<<<<<<< HEAD
<<<<<<< HEAD
- cd qmcpy
- make all
- cd ..
=======
- make qrng
>>>>>>> documentation updates

install:
<<<<<<< HEAD
- pip install --quiet -r requirements/level_1_add_tests.txt
=======
- pip install --quiet -r requirements/dev.txt
>>>>>>> reference updates
=======
- make qrng

install:
- pip install --quiet -r requirements/dev.txt
>>>>>>> 389b9cbbb73caab4f2f84edd6a5b380f2fec2058
- pip install -e .

script:
- coverage run --source=./ -m unittest discover -s test/fasttests
- coverage run --append --source=./ -m unittest discover -s test/longtests


after_success:
- codecov