site_name: "QMCPy"
nav:
  - Quasi Monte Carlo Software: index.md
  - API:
    - Discrete Distributions: discrete_distributions.md
    - True Measures: true_measures.md
    - Integrands: integrands.md
    - Stopping Criteria: stopping_criteria.md
    - Util: util.md
  # - Demos:
  #   - Fast GP Net: examples/simple/fgp_dnb2.ipynb
  - Development:
    - Citing QMCPy: citation.md
    - Community: community.md
    - Contributing: CONTRIBUTING.md
    - License: https://github.com/QMCSoftware/QMCSoftware/blob/master/LICENSE
    - Sponsors: sponsors.md
    - Select References: select_references.md
  - Printable Docs: print_page/

plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - mkdocstrings:
      #enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      #custom_templates: templates
      default_handler: python
      handlers:
        python:
          paths: [qmcpy]  # search packages in the src folder
          options:
            members_order: source
            show_root_toc_entry: false
            heading_level: 3
            docstring_section_style: table
            separate_signature: true
            line_length: 50
            show_submodules: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
  - print-site # enables generating pdf by saving docs in print_page/ https://timvink.github.io/mkdocs-print-site-plugin/index.html 
  
theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: cyan
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: cyan
  name: material
  navigation_depth: 6
  color_mode: auto
  user_color_mode_toggle: True
  features:
    - navigation.expand
    - toc.follow
    - navigation.sections
    - toc.integrate
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - toc
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js