name: qmcpy
channels:
  - umontreal-simul
  - conda-forge
  - defaults
dependencies:
  - appmode=0.8.0=py37hc8dfbb8_2
  - appnope=0.1.0=py37hc8dfbb8_1002
  - argon2-cffi=20.1.0=py37h60d8a13_2
  - async_generator=1.10=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bzip2=1.0.8=haf1e3a3_3
  - ca-certificates=2020.6.20=hecda079_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1002
  - freetype=2.10.4=ha233b18_0
  - importlib_metadata=2.0.0=1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=py_2
  - jupyter_core=4.6.3=py37hc8dfbb8_2
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - latnetbuilder=2.1.1=py37_0
  - lcms2=2.11=h174193d_0
  - libblas=3.9.0=2_openblas
  - libcblas=3.9.0=2_openblas
  - libcxx=11.0.0=h439d374_0
  - libffi=3.2.1=hb1e8313_1007
  - libgfortran=5.0.0=h7cc5361_13
  - libgfortran5=9.3.0=h7cc5361_13
  - liblapack=3.9.0=2_openblas
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=h7cec526_2
  - libsodium=1.0.18=haf1e3a3_1
  - libtiff=4.1.0=h2ae36a8_6
  - libwebp-base=1.1.0=h0b31af3_3
  - llvm-openmp=11.0.0=h73239a0_1
  - lz4-c=1.9.2=hb1e8313_3
  - markupsafe=1.1.1=py37h395d20d_2
  - mistune=0.8.4=py37h60d8a13_1002
  - nbclient=0.5.1=py_0
  - ncurses=6.2=hb1e8313_2
  - nest-asyncio=1.4.1=py_0
  - numexpr=2.7.1=py37h6d0141a_3
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.0.2u=h0b31af3_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandocfilters=1.4.2=py_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.1=py37hf860fee_0
  - pip=20.2.4=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.7.0=h145921a_1006
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - readline=7.0=hcfe32e1_1001
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37h2987424_2
  - simplegeneric=0.8.1=py_1
  - sqlite=3.28.0=h9721f7c_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_1
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py37hc8dfbb8_4
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.3=hb1e8313_2
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.5=h289c70a_2
  - pip:
    - alabaster==0.7.12
    - astroid==2.4.2
    - attrs==19.3.0
    - babel==2.8.0
    - backcall==0.1.0
    - bleach==3.1.5
    - certifi==2020.4.5.1
    - cffi==1.14.0
    - chardet==3.0.4
    - codecov==2.1.5
    - commonmark==0.9.1
    - coverage==5.1
    - cryptography==3.2
    - dataclasses==0.6
    - docutils==0.16
    - future==0.18.2
    - idna==2.9
    - imagesize==1.2.0
    - importlib-metadata==1.6.0
    - iniconfig==1.1.1
    - ipykernel==5.2.1
    - ipython==7.14.0
    - isort==5.7.0
    - jedi==0.17.0
    - jeepney==0.4.3
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - keyring==21.2.1
    - kiwisolver==1.2.0
    - lazy-object-proxy==1.4.3
    - markdown==3.2.2
    - matplotlib==3.2.1
    - mccabe==0.6.1
    - more-itertools==8.4.0
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - notebook==6.1.5
    - numpy==1.18.5
    - pandas==1.0.3
    - pandoc==1.0.2
    - parso==0.7.0
    - pkginfo==1.5.0.1
    - pluggy==0.13.1
    - ply==3.11
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - py==1.8.2
    - pydeps==1.9.13
    - pygments==2.6.1
    - pylint==2.6.0
    - pyrsistent==0.16.0
    - pytest==6.2.1
    - pytz==2020.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - readme-renderer==26.0
    - recommonmark==0.6.0
    - requests==2.23.0
    - requests-toolbelt==0.9.1
    - scipy==1.4.1
    - secretstorage==3.1.2
    - six==1.14.0
    - snowballstemmer==2.0.0
    - sphinx==3.0.3
    - sphinx-markdown-tables==0.0.14
    - sphinx-math-dollar==1.1.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - stdlib-list==0.8.0
    - terminado==0.8.3
    - toml==0.10.2
    - torch==1.7.0
    - tornado==6.0.4
    - tqdm==4.46.1
    - traitlets==4.3.3
    - twine==3.1.1
    - typed-ast==1.4.2
    - typing-extensions==3.7.4.3
    - urllib3==1.25.9
    - wcwidth==0.1.9
    - wrapt==1.12.1
    - zipp==3.1.0
